=== ronnniedev/EjerciciosMarcas/Tema 4/TareadeEntrega2/tareadeentrega2.dtd
<!ELEMENT hardwareCatalog (item+)>
<!ELEMENT item (id,type,brand,model,especifications)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT especifications (#PCDATA)>

=== ronnniedev/EjerciciosMarcas/Tema 4/TareadeEntrega2/tareadeentrega2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hardwareCatalog SYSTEM "tareadeentrega2.dtd">
<?xml-stylesheet href="tareadeentrega2.css" type="text/css"?>
<hardwareCatalog>
    <item>
        <id>1</id>
        <type>tipazo</type>
        <brand>Ea</brand>
        <model>Portatil Asus 3</model>
        <especifications>360 Gigas</especifications>
    </item>
    <item>
        <id>2</id>
        <type>tipasu</type>
        <brand>Microsoft</brand>
        <model>Sobremesa</model>
        <especifications>Disquetera</especifications>
    </item>
    <item>
        <id>3</id>
        <type>tipin</type>
        <brand>Ubisoft</brand>
        <model>Portatil Genius</model>
        <especifications>Teclado brillante</especifications>
    </item>
</hardwareCatalog>
