=== ronnniedev/EjerciciosMarcas/Tema 4/Examen/prueba.dtd
<!ELEMENT personas (persona+)>
    <!ELEMENT persona (nombre+,apellido?,apellido?,nacimiento?,direccion+,varon?)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT varon EMPTY>
    <!ELEMENT nacimiento EMPTY>
    <!ELEMENT direccion (calle?,poblacion?,provincia?,cpostal)>
    <!ELEMENT calle (#PCDATA)>
    <!ELEMENT poblacion (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT cpostal (#PCDATA)>
    <!ATTLIST nacimiento dia CDATA #REQUIRED>
    <!ATTLIST nacimiento mes CDATA #REQUIRED>
    <!ATTLIST nacimiento anyo CDATA #REQUIRED>

=== ronnniedev/EjerciciosMarcas/Tema 4/Examen/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "prueba.dtd">
<personas>
    <persona>
        <nombre>Juan</nombre>
        <apellido>Pardo</apellido>
        <nacimiento dia="26" mes="abril" anyo="1995"/>
        <direccion>
            <calle>Maricarmen Villavieja</calle>
            <poblacion>Gijon</poblacion>
            <cpostal>33207</cpostal>
        </direccion>
        <varon/>
    </persona>
    <persona>
        <nombre>Maria</nombre>
        <nacimiento dia="30" mes="Mayo" anyo="2000"/>
        <direccion>
            <calle>Teodoro Cuesta</calle>
            <provincia>Asturias</provincia>
            <cpostal>33208</cpostal>
        </direccion>
    </persona>
    <persona>
        <nombre>Pelayo</nombre>
        <apellido>Gonzalez</apellido>
        <apellido>Garcia</apellido>
        <direccion>
            <provincia>Catalu√±a</provincia>
            <cpostal>33100</cpostal>
        </direccion>
        <varon/>
    </persona>
</personas>
