=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer1.dtd
<!ELEMENT listaventas (venta+)>
    <!ELEMENT venta (importe,comprador,vendedor,fecha?,codFactura)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codFactura (#PCDATA)>

=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas SYSTEM "ejer1.dtd">
<listaventas>
    <venta>
        <importe>100€</importe>
        <comprador>Pepe</comprador>
        <vendedor>Juan</vendedor>
        <fecha>20240207</fecha>
        <codFactura>cod1</codFactura>
    </venta>
    <venta>
        <importe>100€</importe>
        <comprador>Pepe</comprador>
        <vendedor>Juan</vendedor>
        <fecha>20240207</fecha>
        <codFactura>cod1</codFactura>
    </venta>
</listaventas>
