=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer4.dtd
<!ELEMENT listaventas (venta*)>
    <!ELEMENT venta (importe,comprador,vendedor,fecha?)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ATTLIST venta codFactura ID #REQUIRED>

=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas SYSTEM "ejer4.dtd">
<listaventas>
    <venta codFactura="f22">
        <importe>50 euros</importe>
        <comprador>Mauricio</comprador>
        <vendedor>Sony</vendedor>
    </venta>
    <venta codFactura="f23">
        <importe>50 euros</importe>
        <comprador>Mauricio</comprador>
        <vendedor>Sony</vendedor>
    </venta>
</listaventas>
