=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer5.dtd
<!ELEMENT listacompras (venta*)>
    <!ELEMENT venta (ventacredito|ventainmediata)>
    <!ELEMENT ventacredito (fechaimpago?,cantidad)>
    <!ELEMENT ventainmediata (cantidad,divisa)>
    <!ELEMENT fechaimpago (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT divisa (#PCDATA)>

=== ronnniedev/EjerciciosMarcas/Tema 4/Actividad2/ejer5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacompras SYSTEM "ejer5.dtd">
<listacompras>
    <venta>
        <ventacredito>
            <cantidad>32 euros</cantidad>
        </ventacredito>
    </venta>
    <venta>
        <ventacredito>
            <fechaimpago> 23 de Marzo</fechaimpago>
            <cantidad>32</cantidad>
        </ventacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>23</cantidad>
            <divisa>euros</divisa>
        </ventainmediata>
    </venta>
</listacompras>
